[workspace]
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
channels = ["conda-forge"]
name = "playground2"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
run-analysis = "python main.py"

[dependencies]
